task_name: servicenow_cs_en_es
extends: ["./base.yaml#"]
dataset_path: ServiceNow-AI/asr_codeswitched
subset: en_es
language: en/es
audio_column: audio
target_column: utterance
postprocessor: CodeSwitchAerPostprocessor
metrics:
  - metric: word_error_rate
  - metric: codeswitched_wer
  - metric: llm_judge_aer
user_prompt: |
  Transcribe the following audio exactly as spoken. Output only the transcript with no prefix text.
